services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      - redis

  queue_manager:
    build: ./queue_manager
    container_name: queue_manager
    ports:
      - "8001:8001"
    depends_on:
      - redis

  worker1:
    build: ./worker
    container_name: worker1
    depends_on:
      - redis
      - queue_manager

  worker2:
    build: ./worker
    container_name: worker2
    depends_on:
      - redis
      - queue_manager
